// Multi-touch control test (CDP touch events, landscape phone): steer slider + gas + drift + item held simultaneously; verifies input state and that the kart responds.
import { serve, launch } from '../tools/apptest.mjs'; import fs from 'fs';
const sleep = (ms) => new Promise(r => setTimeout(r, ms)); const { srv, port } = await serve(); const { b, pg, logs } = await launch(844, 390, { mobile: true });
await pg.goto(`http://localhost:${port}/index.html?autostart=1&track=meadow&laps=3`); await pg.waitForFunction('window.__app && __app.race', { timeout: 120000, polling: 300 }); await pg.waitForFunction('__app.race.state==="racing"', { timeout: 120000, polling: 300 });
const rect = async (sel) => pg.evaluate((q) => { const r = document.querySelector(q).getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2, w: r.width, h: r.height, l: r.x }; }, sel);
const S = () => pg.evaluate(() => ({ ...__test.input.state, kartSteer: __app.race.localKart.sim.steer, spd: __app.race.localKart.sim.s, drifting: __app.race.localKart.sim.drift.on, t: __app.race.t }));
const out = []; const rec = async (name, extra = {}) => { await sleep(900); const s = await S(); out.push({ name, ...s, ...extra }); console.log(name, JSON.stringify({ steer: +s.steer.toFixed(2), gas: s.gas, brake: s.brake, drift: s.drift, spd: +s.spd.toFixed(1), kartSteer: +s.kartSteer.toFixed(2) })); };
const sl = await rect('#tcSlider'), gas = await rect('#tcGas'), drift = await rect('#tcDrift'), item = await rect('#tcItem'), brake = await rect('#tcBrake');
await rec('idle'); const t1 = await pg.touchscreen.touchStart(gas.x, gas.y); await rec('gas held');
const t2 = await pg.touchscreen.touchStart(sl.l + sl.w * 0.95, sl.y); await rec('steer right + gas'); await t2.move(sl.l + sl.w * 0.05, sl.y); await rec('steer left + gas');
const t3 = await pg.touchscreen.touchStart(drift.x, drift.y); await rec('drift + steer + gas'); const t4 = await pg.touchscreen.touchStart(item.x, item.y); await rec('+ item');
await t4.end(); await t3.end(); await t2.end(); await rec('released steer/drift/item (gas still held)'); await t1.end(); const t5 = await pg.touchscreen.touchStart(brake.x, brake.y); await rec('brake'); await t5.end(); await rec('all released');
const g = (n) => out.find(o => o.name === n); const checks = [['gas registers', g('gas held').gas], ['steer right ~ +1', g('steer right + gas').steer > 0.8], ['steer left ~ -1', g('steer left + gas').steer < -0.8], ['multi-touch: drift+steer+gas simultaneously', g('drift + steer + gas').drift && g('drift + steer + gas').gas && g('drift + steer + gas').steer < -0.5], ['steer returns to 0 on release', Math.abs(g('released steer/drift/item (gas still held)').steer) < 0.01], ['brake registers', g('brake').brake === 1], ['kart actually moves on gas', g('steer right + gas').spd > 5]];
for (const [n, ok] of checks) console.log(ok ? 'PASS' : 'FAIL', n); await pg.screenshot({ path: '/workspace/kart-racer/shots/touch_test_landscape.png' });
fs.writeFileSync('tests/results/touch.json', JSON.stringify({ checks: checks.map(([n, ok]) => ({ n, ok: !!ok })), samples: out, errors: logs }, null, 1)); console.log('errors', logs.length); await b.close(); srv.close();
