# id|name|cup|theme|length_m|avg_speed_ms|bpm|key|shortcut|hazard|landmark|item_notes|reverse_notes|ambience
TRACKS_RAW = """
1|Buttercup Meadows|Seedling Cup|Sunny meadow valley with windmills, sunflower fields and a covered bridge|1640|32|122|C major|Hay-bale gap through the sunflower field behind the windmill; rough ground, a boost pad at the entry saves about 2.5 s|Sheep herd crosses the hairpin; a bell rings 2 s before they step out|Giant windmill whose blades sweep over the finish straight|First item row sits 260 m after the grid and spans the full road width on the long first straight; second row is after the covered bridge|Reverse swaps the hay-bale gap entry to the left-hand side and moves the sheep crossing to the bridge exit|Birdsong, wind, distant cowbells, light crowd on the grandstand
2|Lantern Harbor|Seedling Cup|Night port with paper lanterns, cranes and moored ships|1980|33|126|A minor|Slip through the container row; container doors open and close on a 6 s cycle, a closed door costs a wall bump|Crane loads swing over the dockside straight, shown by a ground shadow 1.2 s early|Lighthouse tower with a rotating beam that lights the track|Item rows sit on the wide pier after turn 2 and before the container row so a shortcut hopeful can arrive with an item|Reverse flips the container cycle phase so the doors are closed when you arrive on lap 1|Gulls, ship horns, water lapping, crowd cheer from pier
3|Mirage Mesa|Seedling Cup|Desert canyon with sandstone arches and a dry riverbed|2240|35|118|D dorian|Jump the dry riverbed through the twin arch over a sand ramp; needs a mini-turbo to hold speed on the sand|Boulders roll from the canyon wall in the narrows, each telegraphed by a dust puff|Twin Arch rock formation|Item rows after the first arch and at the end of the canyon; none within 120 m of the narrows entry|Reverse moves the boulder gap to the other canyon wall and replaces the sand ramp with a cliff-edge ramp|Desert wind, distant hawk cries, rolling dust, low crowd
4|Frostbite Pass|Seedling Cup|Snowy mountain pass with an ice cave and a frozen waterfall|2060|34|110|E minor|Ice-cave tunnel through the mountain; slippery surface unless you hold a drift line|Icicles drop in the cave with a shadow telegraph; ice patches on the outside bend|Frozen waterfall next to a cable car line|Item rows before the cave and on the downhill straight; no rows inside the cave|Reverse sends you through the cave uphill with ice patches placed on the new entry|Howling wind, creaking cable car, snow crunch
5|Clockwork Quarter|Copper Cup|Steampunk city with giant gears and brass pipes|1320|31|132|G minor|Slip through the gear tower; timed gate opens every 8 s|Rotating cog-bars and steam vents at the central square|Giant clock tower that chimes on the hour (music syncs)|Compact track: two item rows only, after the second corner and before the square|Reverse swaps the gear tower gate to the exit and adds a steam vent at the new entry|Ticking, steam hiss, distant factory whistles
6|Coral Causeway|Copper Cup|Underwater glass tunnels over a coral reef|2520|34|116|F lydian|Kelp-forest cut-through with current streams that boost your speed|Pufferfish mines drift across the road, they inflate when you approach|A giant whale gliding overhead|Rows sit before each glass tunnel exit; one row inside the kelp shortcut for risk-reward|Reverse flips the current direction in the kelp shortcut so it becomes a slow gap|Muffled water, bubbles, distant whale song
7|Jade Terrace|Copper Cup|Terraced mountain gardens with stone lanterns and a pagoda|2780|35|104|D pentatonic|Bamboo bridge between terraces; narrow, no walls|Swinging log gate at the temple steps|Five-storey pagoda|Item rows on terraces 1 and 3; none on the bridge|Reverse shifts the log gate timing and replaces the bridge entrance with a ramp|Wind chimes, bamboo creak, temple bell
8|Moonlit Orchard|Copper Cup|Cute spooky orchard with friendly ghosts and lanterns|1900|33|128|B minor|Run through the hollow giant tree; slow bark floor, but it saves a hairpin|Mischievous scarecrows lean into the road after a hidden cue|Giant gnarled tree glowing with lanterns|Item rows after the orchard hairpin and before the hollow tree|Reverse puts the scarecrows on the opposite verge|Crickets, owls, creaking branches, ghostly giggles
9|Magma Foundry|Tempest Cup|Volcano forge with lava rivers and anvils|2150|34|138|C# phrygian|Cross the cooled lava crust; it is slow rough ground but cuts a long bend|Lava geysers burst with a glowing telegraph; forge hammers swing over the road|Colossal anvil statue|Rows before the forge hall and after the lava bridge|Reverse moves the geysers to the exit side|Rumbling, forge clangs, bubbling lava
10|Cloudtop Carnival|Tempest Cup|Sky fairground on clouds with ferris wheel and roller-coaster|2360|34|134|F major|Ride the roller-coaster rail section, boost pad at the entrance|Bumper-car clusters shuffle across the road|Giant ferris wheel with spinning gondolas|Rows after the carousel and before the rail shortcut|Reverse flips the rail direction so it climbs instead of drops|Fair music loops, laughing crowd, clinking rides
11|Stormwatch Cliffs|Tempest Cup|Coastal cliffs with a lighthouse and an incoming storm|3100|37|112|A minor|Dive into the sea cave beneath the arch; waves surge on a 10 s cycle|Lightning strikes on exposed bends, telegraphed by a ring of light|Tall lighthouse sending beams into the storm|Rows at the cliff top and after the coastal bridge|Reverse changes the wave cycle and puts the lightning ring on the opposite bend|Crashing waves, thunder, gull cries
12|Glowcap Caverns|Tempest Cup|Crystal caves with bioluminescent mushrooms|1780|32|124|E dorian|Cross the crystal bridge over the chasm; narrow, no walls|Stalactites drop with a shadow warning|Crystal Cathedral, a huge glowing cavern|Rows before the cathedral and after the chasm|Reverse puts the stalactite drops on the exit stretch|Dripping, echoing hum, crystal chimes
13|Starlight Spaceport|Zenith Cup|Launch complex with gantries, fuel tanks and rockets|2640|36|142|F# minor|Cut through the launch gantry; gate opens briefly|Rocket exhaust blasts across the road on a timer|A rocket that launches during lap 3|Rows after the tank farm and before the gantry|Reverse swaps the exhaust timing and moves the launch cutscene to lap 2|Countdown PA announcements, humming engines, distant crowd
14|Neon Metro Loop|Zenith Cup|Night city with holograms, a tram and skyscrapers|2900|36|140|G minor|Run through the rail yard under the tram|Trams cross the road, indicated by flashing lights and a bell|Skyscraper with a holographic dragon|Rows on the boulevard and after the rail yard|Reverse makes the tram cross on the other side|City hum, tram bells, distant sirens, holographic chime
15|Overgrowth Ruins|Zenith Cup|Jungle temple with vines, waterfalls and a stone face|2430|35|120|C phrygian|Dash through the collapsed temple hall; rubble slows you|Rolling stone drum that rolls down the stairs on a timer|Giant stone face carved in the cliff|Rows before the temple, none inside the hall|Reverse sends the rolling stone up the stair instead|Jungle birds, waterfall, drums
16|Zenith Ring|Zenith Cup|Anti-gravity ring in the sky around a ringed planet|3400|38|150|A minor|Take the gravity-flip loop in the inner ring; requires boost to climb|Asteroid pulses along the outer ring|A ringed planet|Rows on each ring segment, none on the climb|Reverse flips the gravity direction so the climb is a drop|Deep space hum, energy swell, distant announcer
17|Rustbelt Rally|Bonus|Industrial scrapyard with crushed-car mountains|1090|32|130|B minor|Climb the scrap ramp over the car pile|Magnet crane lifts cars across the road|Mountain of crushed cars|Item rows after the crusher|Reverse swaps the ramp direction|Clanking, grinding, distant welding
18|Sugarplum Speedway|Bonus|Candy land with lollipop trees and chocolate rivers|1560|32|136|D major|Slide down the chocolate slope between candy canes|Gumdrop bumper clusters pop out of the sugar|Giant lollipop tree|Item rows on the sugar plaza|Reverse flips the chocolate slope into a climb|Cheerful chimes, popping candy, crowd
19|Polar Lights Circuit|Bonus|Ice rink under the aurora with a snowman crowd|1250|31|114|F# dorian|Cut across the frozen pond infield|Ice patches in the corners|Aurora ribbons over a giant snowman|Item rows on the straight|Reverse moves the frozen pond entry|Soft wind, ice creaks, distant skates
20|Thunderhead Savanna|Bonus|Safari plains with herds, acacia trees and a dust storm|3300|37|108|G mixolydian|Cross the dry waterhole|Herd of wildebeest crosses the road, signalled by dust|Giant baobab tree|Rows on the plains stretch and after the waterhole|Reverse moves the herd crossing and changes the waterhole entry|Wind in grass, distant animals, drums
"""
def tracks():
    out=[]
    for l in TRACKS_RAW.strip().split("\n"):
        p=l.split("|")
        assert len(p)==14, (len(p), l[:30])
        keys=["id","name","cup","theme","length","avg","bpm","key","shortcut","hazard","landmark","items","reverse","ambience"]
        d=dict(zip(keys,p)); d["id"]=int(d["id"]); d["length"]=int(d["length"]); d["avg"]=float(d["avg"]); d["bpm"]=int(d["bpm"])
        d["laptime"]=round(d["length"]/d["avg"],1)
        out.append(d)
    return out
