// Versus lobby UI: host a room (6-char code) or join one. Real WebRTC via net.js; labelled offline fallback when signalling fails.
import { Session, normCode, fmtCode, MAX_HUMANS } from './net.js';
export function mountLobby(app, T) {
  const d = app.screenEl(); const ui = app.ui; const s = app.save;
  const profile = () => ({ name: s.sel.char, build: s.builds[s.sel.body] });
  const net = app.net; const esc = (x) => String(x).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
  const note = `<div style="font-size:11px;color:var(--mut);margin-top:8px;line-height:1.4">Peer-to-peer over WebRTC (PeerJS broker for the handshake + Google STUN). Up to ${MAX_HUMANS} players; CPU racers fill the grid to 12. No TURN relay, so some strict mobile/corporate networks cannot connect. Host must keep this screen open.</div>`;
  const back = () => { ui('ui_back'); if (app.net) { app.net.close(); app.net = null; } app.show('menu'); };
  const fallback = `<button class="btn blue" id="fb">Offline fallback: race 11 CPU rivals</button>`;
  const bindFb = () => { const f = d.querySelector('#fb'); if (f) f.onclick = () => { ui('ui_confirm'); if (app.net) { app.net.close(); app.net = null; } app.mode = 'quick'; app.show('setup'); }; };

  if (!net) {
    const pre = app.pendingRoom || '';
    d.innerHTML = `<div class="topbar"><h2>Versus · room code</h2>${app.coinsBadge ? app.coinsBadge() : ''}</div>
    <div class="grow col scroll" style="gap:10px"><div class="panel" style="padding:14px"><b>Host a room</b><div style="font-size:12px;color:var(--mut);margin:4px 0 10px">You get a 6-character code to share with up to 3 friends.</div><button class="btn" id="host">Create room</button></div>
    <div class="panel" style="padding:14px"><b>Join a room</b><div class="row" style="margin-top:8px;gap:8px"><input id="code" maxlength="7" placeholder="ABC 123" value="${pre}" autocomplete="off" autocapitalize="characters" spellcheck="false" style="flex:1;font-size:26px;font-weight:900;letter-spacing:.2em;text-align:center;text-transform:uppercase;padding:10px;border-radius:12px;border:2px solid rgba(255,255,255,.25);background:rgba(0,0,0,.35);color:#fff;min-width:0"><button class="btn blue" id="join">Join</button></div>${note}</div></div>
    <div class="row"><button class="btn ghost" id="back">Back</button></div>`;
    d.querySelector('#back').onclick = back;
    d.querySelector('#host').onclick = () => { ui('ui_confirm'); const n = app.net = new Session(app); n.onChange = () => app.screen === 'lobby' && app.show('lobby'); n.cfg.track = app.cfg.track || 'meadow'; n.cfg.laps = app.cfg.laps || 3; n.host(profile()); app.show('lobby'); };
    const doJoin = () => { const c = normCode(d.querySelector('#code').value); if (c.length !== 6) { ui('ui_error'); app.toast('Enter the 6-character code', '#ff8a8a'); return; } ui('ui_confirm'); const n = app.net = new Session(app); n.onChange = () => app.screen === 'lobby' && app.show('lobby'); n.join(c, profile()); app.show('lobby'); };
    d.querySelector('#join').onclick = doJoin; const inp = d.querySelector('#code'); inp.oninput = () => { const c = normCode(inp.value); inp.value = c.length > 3 ? c.slice(0, 3) + ' ' + c.slice(3) : c; };
    if (pre) { app.pendingRoom = ''; setTimeout(doJoin, 50); }
    return;
  }
  // session screens
  if (net.status === 'connecting') { d.innerHTML = `<div class="topbar"><h2>Versus · room code</h2></div><div class="grow row" style="justify-content:center;align-items:center"><div class="panel" style="padding:20px;text-align:center"><b>${net.role === 'host' ? 'Opening room…' : 'Connecting to ' + fmtCode(net.code) + '…'}</b><div style="font-size:12px;color:var(--mut);margin-top:6px">Contacting the PeerJS signalling server</div></div></div><div class="row"><button class="btn ghost" id="back">Cancel</button></div>`; d.querySelector('#back').onclick = back; return; }
  if (net.status === 'error' || net.status === 'lost') { d.innerHTML = `<div class="topbar"><h2>Versus · room code</h2></div><div class="grow col" style="justify-content:center;gap:10px"><div class="panel" style="padding:16px"><b style="color:#ff8a8a">Online unavailable</b><div style="margin-top:6px;font-size:13px">${esc(net.error)}</div>${note}</div>${fallback}</div><div class="row"><button class="btn ghost" id="back">Back</button><div class="grow"></div><button class="btn" id="retry">Try again</button></div>`; d.querySelector('#back').onclick = back; d.querySelector('#retry').onclick = () => { ui('ui_click'); app.net.close(); app.net = null; app.show('lobby'); }; bindFb(); return; }
  const host = net.role === 'host'; const cfg = net.cfg; const art = { meadow: '#6bc24a', harbor: '#2f6f8a', mesa: '#e0a65a', frost: '#cfe6ff' };
  const slots = []; for (let i = 0; i < MAX_HUMANS; i++) { const m = net.members[i]; slots.push(m ? `<div class="pl"><span class="dot" style="background:${m.ready ? '#5be37d' : '#ffd23f'}"></span><b>${esc(m.name)}</b>${m.pid === net.myPid ? '<em> (you)</em>' : ''}${m.pid === 0 ? '<em> · host</em>' : ''}<span class="r">${m.ready ? 'ready' : 'waiting'}</span></div>` : `<div class="pl empty"><span class="dot" style="background:#456"></span>open slot</div>`); }
  const nReady = net.members.filter(m => m.ready).length;
  d.innerHTML = `<style>.pl{display:flex;align-items:center;gap:8px;padding:9px 10px;border-radius:10px;background:rgba(255,255,255,.08);margin-bottom:6px;font-size:14px}.pl.empty{opacity:.45}.pl .dot{width:10px;height:10px;border-radius:50%}.pl em{font-style:normal;opacity:.65;font-size:12px}.pl .r{margin-left:auto;font-size:11px;opacity:.7}.codebig{font-size:44px;font-weight:900;letter-spacing:.14em;line-height:1;color:var(--y);text-shadow:0 3px 0 rgba(0,0,0,.35)}</style>
  <div class="topbar"><h2>${host ? 'Your room' : 'Room'} · <span style="color:var(--y)">${fmtCode(net.code)}</span></h2><span class="pill" style="background:#1f7a3d">${net.stats.rtt ? Math.round(net.stats.rtt) + ' ms' : 'connected'}</span></div>
  <div class="grow row wrap scroll" style="gap:10px;align-items:flex-start"><div class="panel" style="padding:12px;flex:1;min-width:250px">${host ? `<div class="row sp" style="align-items:center"><div><div style="font-size:11px;color:var(--mut);font-weight:800">ROOM CODE</div><div class="codebig">${fmtCode(net.code)}</div></div><button class="btn blue" id="share" style="padding:8px 14px">Share</button></div><div style="height:10px"></div>` : ''}<div style="font-size:11px;color:var(--mut);font-weight:800;margin-bottom:6px">PLAYERS (${net.members.length}/${MAX_HUMANS})</div>${slots.join('')}</div>
  <div class="panel" style="padding:12px;flex:1;min-width:250px"><div style="font-size:11px;color:var(--mut);font-weight:800">TRACK</div><div class="row wrap" style="gap:6px;margin:6px 0">${['meadow', 'harbor', 'mesa', 'frost'].map(id => `<button class="btn ${cfg.track === id ? '' : 'ghost'}" data-t="${id}" ${host ? '' : 'disabled'} style="padding:8px 12px;font-size:13px">${app.TRACK_DEFS[id].name}</button>`).join('')}</div>
  <div class="row wrap" style="gap:14px"><div><div style="font-size:11px;color:var(--mut);font-weight:800">LAPS</div><div class="seg" id="laps">${[1, 2, 3, 4, 5].map(n => `<button data-n="${n}" class="${cfg.laps === n ? 'on' : ''}" ${host ? '' : 'disabled'}>${n}</button>`).join('')}</div></div>
  <div class="toggle" style="gap:8px"><span>Items</span><div class="sw2 ${cfg.items ? 'on' : ''}" data-o="items"></div></div><div class="toggle" style="gap:8px"><span>CPU fill to 12</span><div class="sw2 ${cfg.cpu ? 'on' : ''}" data-o="cpu"></div></div></div>${note}</div></div>
  <div class="row"><button class="btn ghost" id="back">Leave</button><div class="grow"></div>${host ? `<span style="font-size:12px;color:var(--mut);align-self:center">${nReady}/${net.members.length} ready</span><button class="btn" id="start" style="font-size:18px;padding:14px 34px">Start race</button>` : `<button class="btn ${net.members.find(m => m.pid === net.myPid)?.ready ? 'blue' : ''}" id="rdy" style="font-size:18px;padding:14px 34px">${net.members.find(m => m.pid === net.myPid)?.ready ? 'Ready ✓' : "I'm ready"}</button>`}</div>`;
  d.querySelector('#back').onclick = back;
  if (host) {
    d.querySelectorAll('[data-t]').forEach(b => b.onclick = () => { ui('ui_click'); net.setCfg({ track: b.dataset.t }); });
    d.querySelectorAll('#laps button').forEach(b => b.onclick = () => { ui('ui_toggle'); net.setCfg({ laps: +b.dataset.n }); });
    d.querySelectorAll('[data-o]').forEach(t => t.onclick = () => { ui('ui_toggle'); net.setCfg({ [t.dataset.o]: !cfg[t.dataset.o] }); });
    d.querySelector('#start').onclick = () => { if (net.members.length < 2 && !cfg.cpu) { ui('ui_error'); app.toast('Need another player or CPU fill', '#ff8a8a'); return; } ui('ui_confirm'); net.hostStart(app.makeCpuBuild, app.CPU_NAMES); };
    d.querySelector('#share').onclick = async () => { ui('ui_click'); const url = location.origin + location.pathname + '?room=' + net.code; try { if (navigator.share) await navigator.share({ title: 'Sparkdrift GP', text: 'Join my kart race! Code ' + fmtCode(net.code), url }); else { await navigator.clipboard.writeText(url); app.toast('Link copied'); } } catch (e) { try { await navigator.clipboard.writeText(url); app.toast('Link copied'); } catch (x) { app.toast(url); } } };
  } else { d.querySelector('#rdy').onclick = () => { const me = net.members.find(m => m.pid === net.myPid); ui('lobby_ready'); net.ready(!(me && me.ready)); }; }
}
