// GENERATED by tools/mk_trackdefs.py. Layouts are turtle programs (straights/arcs) closed by two adjustable straights.
export const TRACK_DEFS = {
 "meadow": {
  "id": "meadow",
  "name": "Buttercup Meadows",
  "cup": "Seedling Cup",
  "order": 1,
  "theme": "meadow",
  "width": 15,
  "offroad": 9,
  "mapOrder": 1,
  "bpm": 122,
  "music": "buttercup",
  "amb": "meadow",
  "env": "open",
  "shortcut": {
   "pts": [
    [
     429.3,
     -7.02
    ],
    [
     434.99,
     -26.77
    ],
    [
     435.12,
     -72.97
    ],
    [
     435.18,
     -96.77
    ],
    [
     435.24,
     -120.57
    ],
    [
     435.36,
     -166.76
    ],
    [
     425.27,
     -181.66
    ]
   ],
   "width": 11,
   "surface": "rough",
   "s1": 614,
   "s2": 894,
   "side": 1
  },
  "rows": [
   0.13,
   0.3,
   0.5,
   0.7,
   0.88
  ],
  "pads": [
   0.22,
   0.6
  ],
  "coinGroups": [
   0.08,
   0.2,
   0.34,
   0.45,
   0.56,
   0.66,
   0.77,
   0.9
  ],
  "hazards": [
   {
    "type": "sheep",
    "f": 0.38
   }
  ],
  "zones": [],
  "landmark": {
   "type": "windmill",
   "f": 0.05,
   "lat": 70
  },
  "prog": [
   [
    "F",
    520
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    50
   ],
   [
    "R",
    50,
    60
   ],
   [
    "F",
    30
   ],
   [
    "L",
    50,
    60
   ],
   [
    "F",
    90
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    130
   ],
   [
    "R",
    80,
    30
   ],
   [
    "F",
    20
   ],
   [
    "L",
    80,
    30
   ],
   [
    "F",
    70
   ],
   [
    "L",
    90,
    50
   ],
   [
    "F",
    150
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    100
   ]
  ],
  "fix": [
   0,
   14
  ],
  "start": 150,
  "scale": 1.176
 },
 "harbor": {
  "id": "harbor",
  "name": "Lantern Harbor",
  "cup": "Seedling Cup",
  "order": 2,
  "theme": "harbor",
  "width": 15,
  "offroad": 9,
  "mapOrder": 2,
  "bpm": 126,
  "music": "lantern",
  "amb": "harbor",
  "env": "metal",
  "shortcut": {
   "pts": [
    [
     422.5,
     0.62
    ],
    [
     407.5,
     -9.38
    ],
    [
     364.73,
     -51.83
    ],
    [
     342.7,
     -73.69
    ],
    [
     320.67,
     -95.56
    ],
    [
     277.9,
     -138.0
    ],
    [
     267.9,
     -153.0
    ]
   ],
   "width": 11,
   "surface": "rough",
   "s1": 1088,
   "s2": 1388,
   "side": 1
  },
  "rows": [
   0.12,
   0.33,
   0.48,
   0.66,
   0.85
  ],
  "pads": [
   0.2,
   0.75
  ],
  "coinGroups": [
   0.06,
   0.18,
   0.3,
   0.42,
   0.55,
   0.68,
   0.8,
   0.92
  ],
  "hazards": [
   {
    "type": "crane",
    "f": 0.1
   },
   {
    "type": "crane",
    "f": 0.8
   },
   {
    "type": "gate",
    "at": "shortcut"
   }
  ],
  "zones": [],
  "landmark": {
   "type": "lighthouse",
   "f": 0.4,
   "lat": 90
  },
  "prog": [
   [
    "F",
    400
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    150
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    260
   ],
   [
    "R",
    90,
    50
   ],
   [
    "F",
    90
   ],
   [
    "L",
    90,
    50
   ],
   [
    "F",
    120
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    300
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    100
   ]
  ],
  "fix": [
   0,
   2
  ],
  "start": 170,
  "scale": 1.1
 },
 "mesa": {
  "id": "mesa",
  "name": "Mirage Mesa",
  "cup": "Seedling Cup",
  "order": 3,
  "theme": "mesa",
  "width": 16,
  "offroad": 9,
  "mapOrder": 3,
  "bpm": 118,
  "music": "mirage",
  "amb": "mesa",
  "env": "canyon",
  "shortcut": {
   "pts": [
    [
     101.51,
     367.01
    ],
    [
     119.03,
     371.28
    ],
    [
     169.35,
     383.65
    ],
    [
     195.28,
     390.02
    ],
    [
     221.2,
     396.39
    ],
    [
     271.52,
     408.77
    ],
    [
     288.77,
     413.82
    ]
   ],
   "width": 11,
   "surface": "sand",
   "s1": 286,
   "s2": 586,
   "side": 1
  },
  "rows": [
   0.14,
   0.36,
   0.55,
   0.74,
   0.9
  ],
  "pads": [
   0.1,
   0.63
  ],
  "coinGroups": [
   0.05,
   0.17,
   0.28,
   0.4,
   0.5,
   0.6,
   0.72,
   0.83
  ],
  "hazards": [
   {
    "type": "boulder",
    "f": 0.45
   },
   {
    "type": "boulder",
    "f": 0.62
   }
  ],
  "zones": [],
  "landmark": {
   "type": "arch",
   "f": 0.2,
   "lat": 60
  },
  "prog": [
   [
    "F",
    250
   ],
   [
    "L",
    60,
    120
   ],
   [
    "R",
    40,
    90
   ],
   [
    "F",
    150
   ],
   [
    "L",
    110,
    70
   ],
   [
    "F",
    120
   ],
   [
    "R",
    60,
    80
   ],
   [
    "F",
    100
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    180
   ],
   [
    "L",
    80,
    90
   ],
   [
    "R",
    50,
    70
   ],
   [
    "F",
    140
   ],
   [
    "L",
    100,
    80
   ],
   [
    "F",
    160
   ],
   [
    "L",
    70,
    120
   ],
   [
    "F",
    100
   ]
  ],
  "fix": [
   12,
   14
  ],
  "start": 150,
  "scale": 0.84
 },
 "frost": {
  "id": "frost",
  "name": "Frostbite Pass",
  "cup": "Seedling Cup",
  "order": 4,
  "theme": "frost",
  "width": 15,
  "offroad": 9,
  "mapOrder": 4,
  "bpm": 110,
  "music": "frost",
  "amb": "frost",
  "env": "ice",
  "shortcut": {
   "pts": [
    [
     133.87,
     466.92
    ],
    [
     136.11,
     484.44
    ],
    [
     175.89,
     495.21
    ],
    [
     196.39,
     500.75
    ],
    [
     216.88,
     506.3
    ],
    [
     256.66,
     517.07
    ],
    [
     266.23,
     531.89
    ]
   ],
   "width": 11,
   "surface": "ice",
   "s1": 434,
   "s2": 664,
   "side": 1
  },
  "rows": [
   0.13,
   0.32,
   0.52,
   0.72,
   0.9
  ],
  "pads": [
   0.2,
   0.8
  ],
  "coinGroups": [
   0.07,
   0.19,
   0.3,
   0.42,
   0.54,
   0.65,
   0.78,
   0.89
  ],
  "hazards": [
   {
    "type": "icicle",
    "f": 0.28
   },
   {
    "type": "icicle",
    "f": 0.5
   },
   {
    "type": "icicle",
    "f": 0.86
   }
  ],
  "zones": [
   {
    "f0": 0.55,
    "f1": 0.62,
    "surface": "ice",
    "onlyRoad": true,
    "lat": [
     -4,
     8
    ]
   }
  ],
  "landmark": {
   "type": "waterfall",
   "f": 0.6,
   "lat": 80
  },
  "prog": [
   [
    "F",
    250
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    120
   ],
   [
    "R",
    140,
    32
   ],
   [
    "F",
    40
   ],
   [
    "L",
    140,
    32
   ],
   [
    "F",
    100
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    250
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    160
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    100
   ]
  ],
  "fix": [
   2,
   8
  ],
  "start": 150,
  "scale": 1.2
 },
 "dusk": {
  "id": "dusk",
  "name": "Firefly Hollow",
  "cup": "Starlight Cup",
  "order": 5,
  "theme": "meadow",
  "skin": "dusk",
  "width": 15,
  "offroad": 9,
  "mapOrder": 5,
  "bpm": 122,
  "music": "buttercup",
  "amb": "meadow",
  "env": "open",
  "shortcut": {
   "pts": [
    [
     89.75,
     389.84
    ],
    [
     97.74,
     405.92
    ],
    [
     108.16,
     445.56
    ],
    [
     113.53,
     465.98
    ],
    [
     118.9,
     486.4
    ],
    [
     129.33,
     526.04
    ],
    [
     139.33,
     541.04
    ]
   ],
   "width": 11,
   "surface": "rough",
   "s1": 304,
   "s2": 564,
   "side": 1
  },
  "rows": [
   0.12,
   0.3,
   0.5,
   0.68,
   0.88
  ],
  "pads": [
   0.2,
   0.62,
   0.8
  ],
  "coinGroups": [
   0.07,
   0.19,
   0.3,
   0.42,
   0.53,
   0.64,
   0.75,
   0.9
  ],
  "hazards": [
   {
    "type": "sheep",
    "f": 0.27
   },
   {
    "type": "sheep",
    "f": 0.72
   }
  ],
  "zones": [],
  "landmark": {
   "type": "windmill",
   "f": 0.55,
   "lat": 70
  },
  "prog": [
   [
    "F",
    151.3
   ],
   [
    "L",
    30,
    33
   ],
   [
    "F",
    169
   ],
   [
    "R",
    60,
    64
   ],
   [
    "F",
    102
   ],
   [
    "L",
    120,
    54
   ],
   [
    "F",
    88
   ],
   [
    "L",
    60,
    67
   ],
   [
    "F",
    210.9
   ],
   [
    "L",
    30,
    67
   ],
   [
    "F",
    54
   ],
   [
    "L",
    60,
    89
   ],
   [
    "F",
    70
   ],
   [
    "R",
    60,
    69
   ],
   [
    "F",
    139
   ],
   [
    "L",
    60,
    50
   ],
   [
    "F",
    56
   ],
   [
    "L",
    120,
    88
   ],
   [
    "F",
    62
   ]
  ],
  "fix": [
   0,
   8
  ],
  "start": 120,
  "scale": 1.0
 },
 "neon": {
  "id": "neon",
  "name": "Neon Docks",
  "cup": "Starlight Cup",
  "order": 6,
  "theme": "harbor",
  "skin": "neon",
  "width": 15,
  "offroad": 9,
  "mapOrder": 6,
  "bpm": 126,
  "music": "lantern",
  "amb": "harbor",
  "env": "metal",
  "shortcut": {
   "pts": [
    [
     196.54,
     415.42
    ],
    [
     206.54,
     400.42
    ],
    [
     209.44,
     351.65
    ],
    [
     210.93,
     326.53
    ],
    [
     212.42,
     301.41
    ],
    [
     215.32,
     252.64
    ],
    [
     223.31,
     236.48
    ]
   ],
   "width": 11,
   "surface": "rough",
   "s1": 464,
   "s2": 754,
   "side": 1
  },
  "rows": [
   0.12,
   0.3,
   0.5,
   0.68,
   0.87
  ],
  "pads": [
   0.22,
   0.78
  ],
  "coinGroups": [
   0.06,
   0.18,
   0.3,
   0.42,
   0.55,
   0.68,
   0.8,
   0.92
  ],
  "hazards": [
   {
    "type": "crane",
    "f": 0.17
   },
   {
    "type": "crane",
    "f": 0.62
   },
   {
    "type": "crane",
    "f": 0.9
   },
   {
    "type": "gate",
    "at": "shortcut"
   }
  ],
  "zones": [],
  "landmark": {
   "type": "lighthouse",
   "f": 0.8,
   "lat": 90
  },
  "prog": [
   [
    "F",
    192.6
   ],
   [
    "L",
    90,
    44
   ],
   [
    "F",
    54
   ],
   [
    "R",
    90,
    40
   ],
   [
    "F",
    131
   ],
   [
    "L",
    90,
    51
   ],
   [
    "F",
    83
   ],
   [
    "L",
    120,
    55
   ],
   [
    "F",
    167
   ],
   [
    "R",
    90,
    82
   ],
   [
    "F",
    273.4
   ],
   [
    "L",
    90,
    64
   ],
   [
    "F",
    178
   ],
   [
    "L",
    45,
    68
   ],
   [
    "F",
    170
   ],
   [
    "L",
    45,
    47
   ],
   [
    "F",
    189
   ],
   [
    "L",
    60,
    65
   ],
   [
    "F",
    179
   ]
  ],
  "fix": [
   0,
   10
  ],
  "start": 120,
  "scale": 0.92
 },
 "ember": {
  "id": "ember",
  "name": "Ember Canyon",
  "cup": "Starlight Cup",
  "order": 7,
  "theme": "mesa",
  "skin": "ember",
  "width": 16,
  "offroad": 9,
  "mapOrder": 7,
  "bpm": 118,
  "music": "mirage",
  "amb": "mesa",
  "env": "canyon",
  "shortcut": {
   "pts": [
    [
     232.57,
     171.67
    ],
    [
     248.73,
     179.66
    ],
    [
     283.94,
     185.03
    ],
    [
     302.07,
     187.8
    ],
    [
     320.21,
     190.57
    ],
    [
     355.42,
     195.94
    ],
    [
     370.42,
     205.94
    ]
   ],
   "width": 11,
   "surface": "sand",
   "s1": 280,
   "s2": 520,
   "side": -1
  },
  "rows": [
   0.12,
   0.34,
   0.52,
   0.72,
   0.9
  ],
  "pads": [
   0.15,
   0.66
  ],
  "coinGroups": [
   0.05,
   0.17,
   0.28,
   0.4,
   0.5,
   0.6,
   0.72,
   0.83
  ],
  "hazards": [
   {
    "type": "boulder",
    "f": 0.3
   },
   {
    "type": "boulder",
    "f": 0.48
   },
   {
    "type": "boulder",
    "f": 0.8
   }
  ],
  "zones": [],
  "landmark": {
   "type": "arch",
   "f": 0.4,
   "lat": 60
  },
  "prog": [
   [
    "F",
    71.5
   ],
   [
    "L",
    30,
    64
   ],
   [
    "F",
    97
   ],
   [
    "L",
    90,
    90
   ],
   [
    "F",
    189
   ],
   [
    "R",
    120,
    44
   ],
   [
    "F",
    81
   ],
   [
    "L",
    180,
    80
   ],
   [
    "F",
    83
   ],
   [
    "R",
    60,
    90
   ],
   [
    "F",
    122
   ],
   [
    "L",
    60,
    65
   ],
   [
    "F",
    127
   ],
   [
    "L",
    90,
    72
   ],
   [
    "F",
    537.5
   ],
   [
    "L",
    60,
    72
   ],
   [
    "F",
    148
   ],
   [
    "L",
    30,
    52
   ],
   [
    "F",
    42
   ]
  ],
  "fix": [
   0,
   14
  ],
  "start": 120,
  "scale": 0.92
 },
 "aurora": {
  "id": "aurora",
  "name": "Aurora Pass",
  "cup": "Starlight Cup",
  "order": 8,
  "theme": "frost",
  "skin": "aurora",
  "width": 15,
  "offroad": 9,
  "mapOrder": 8,
  "bpm": 110,
  "music": "frost",
  "amb": "frost",
  "env": "ice",
  "shortcut": {
   "pts": [
    [
     124.92,
     403.03
    ],
    [
     141.08,
     395.04
    ],
    [
     195.67,
     376.22
    ],
    [
     223.8,
     366.53
    ],
    [
     251.92,
     356.83
    ],
    [
     306.51,
     338.01
    ],
    [
     324.5,
     336.85
    ]
   ],
   "width": 11,
   "surface": "ice",
   "s1": 372,
   "s2": 652,
   "side": 1
  },
  "rows": [
   0.13,
   0.32,
   0.52,
   0.72,
   0.9
  ],
  "pads": [
   0.2,
   0.8
  ],
  "coinGroups": [
   0.07,
   0.19,
   0.3,
   0.42,
   0.54,
   0.65,
   0.78,
   0.89
  ],
  "hazards": [
   {
    "type": "icicle",
    "f": 0.22
   },
   {
    "type": "icicle",
    "f": 0.45
   },
   {
    "type": "icicle",
    "f": 0.68
   },
   {
    "type": "icicle",
    "f": 0.9
   }
  ],
  "zones": [
   {
    "f0": 0.12,
    "f1": 0.18,
    "surface": "ice",
    "onlyRoad": true,
    "lat": [
     -4,
     8
    ]
   }
  ],
  "landmark": {
   "type": "waterfall",
   "f": 0.7,
   "lat": 80
  },
  "prog": [
   [
    "F",
    330.4
   ],
   [
    "L",
    60,
    79
   ],
   [
    "F",
    196
   ],
   [
    "L",
    90,
    77
   ],
   [
    "F",
    329.3
   ],
   [
    "L",
    60,
    44
   ],
   [
    "F",
    214
   ],
   [
    "L",
    60,
    73
   ],
   [
    "F",
    42
   ],
   [
    "R",
    60,
    34
   ],
   [
    "F",
    52
   ],
   [
    "R",
    45,
    35
   ],
   [
    "F",
    209
   ],
   [
    "L",
    180,
    67
   ],
   [
    "F",
    175
   ],
   [
    "R",
    45,
    81
   ],
   [
    "F",
    36.4
   ],
   [
    "L",
    60,
    36
   ],
   [
    "F",
    140
   ]
  ],
  "fix": [
   4,
   16
  ],
  "start": 120,
  "scale": 0.9
 }
};
