// GENERATED by tools/mk_trackdefs.py. Layouts are turtle programs (straights/arcs) closed by two adjustable straights.
export const TRACK_DEFS = {
 "meadow": {
  "id": "meadow",
  "name": "Buttercup Meadows",
  "cup": "Seedling Cup",
  "order": 1,
  "theme": "meadow",
  "width": 15,
  "offroad": 9,
  "mapOrder": 1,
  "bpm": 122,
  "music": "buttercup",
  "amb": "meadow",
  "env": "open",
  "shortcut": {
   "pts": [
    [
     429.3,
     -7.02
    ],
    [
     434.99,
     -26.77
    ],
    [
     435.12,
     -72.97
    ],
    [
     435.18,
     -96.77
    ],
    [
     435.24,
     -120.57
    ],
    [
     435.36,
     -166.76
    ],
    [
     425.27,
     -181.66
    ]
   ],
   "width": 11,
   "surface": "rough",
   "s1": 614,
   "s2": 894,
   "side": 1
  },
  "rows": [
   0.13,
   0.3,
   0.5,
   0.7,
   0.88
  ],
  "pads": [
   0.22,
   0.6
  ],
  "coinGroups": [
   0.08,
   0.2,
   0.34,
   0.45,
   0.56,
   0.66,
   0.77,
   0.9
  ],
  "hazards": [
   {
    "type": "sheep",
    "f": 0.38
   }
  ],
  "zones": [],
  "landmark": {
   "type": "windmill",
   "f": 0.05,
   "lat": 70
  },
  "prog": [
   [
    "F",
    520
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    50
   ],
   [
    "R",
    50,
    60
   ],
   [
    "F",
    30
   ],
   [
    "L",
    50,
    60
   ],
   [
    "F",
    90
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    130
   ],
   [
    "R",
    80,
    30
   ],
   [
    "F",
    20
   ],
   [
    "L",
    80,
    30
   ],
   [
    "F",
    70
   ],
   [
    "L",
    90,
    50
   ],
   [
    "F",
    150
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    100
   ]
  ],
  "fix": [
   0,
   14
  ],
  "start": 150,
  "scale": 1.176
 },
 "harbor": {
  "id": "harbor",
  "name": "Lantern Harbor",
  "cup": "Seedling Cup",
  "order": 2,
  "theme": "harbor",
  "width": 15,
  "offroad": 9,
  "mapOrder": 2,
  "bpm": 126,
  "music": "lantern",
  "amb": "harbor",
  "env": "metal",
  "shortcut": {
   "pts": [
    [
     422.5,
     0.62
    ],
    [
     407.5,
     -9.38
    ],
    [
     364.73,
     -51.83
    ],
    [
     342.7,
     -73.69
    ],
    [
     320.67,
     -95.56
    ],
    [
     277.9,
     -138.0
    ],
    [
     267.9,
     -153.0
    ]
   ],
   "width": 11,
   "surface": "rough",
   "s1": 1088,
   "s2": 1388,
   "side": 1
  },
  "rows": [
   0.12,
   0.33,
   0.48,
   0.66,
   0.85
  ],
  "pads": [
   0.2,
   0.75
  ],
  "coinGroups": [
   0.06,
   0.18,
   0.3,
   0.42,
   0.55,
   0.68,
   0.8,
   0.92
  ],
  "hazards": [
   {
    "type": "crane",
    "f": 0.1
   },
   {
    "type": "crane",
    "f": 0.8
   },
   {
    "type": "gate",
    "at": "shortcut"
   }
  ],
  "zones": [],
  "landmark": {
   "type": "lighthouse",
   "f": 0.4,
   "lat": 90
  },
  "prog": [
   [
    "F",
    400
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    150
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    260
   ],
   [
    "R",
    90,
    50
   ],
   [
    "F",
    90
   ],
   [
    "L",
    90,
    50
   ],
   [
    "F",
    120
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    300
   ],
   [
    "L",
    90,
    45
   ],
   [
    "F",
    100
   ]
  ],
  "fix": [
   0,
   2
  ],
  "start": 170,
  "scale": 1.1
 },
 "mesa": {
  "id": "mesa",
  "name": "Mirage Mesa",
  "cup": "Seedling Cup",
  "order": 3,
  "theme": "mesa",
  "width": 16,
  "offroad": 9,
  "mapOrder": 3,
  "bpm": 118,
  "music": "mirage",
  "amb": "mesa",
  "env": "canyon",
  "shortcut": {
   "pts": [
    [
     101.51,
     367.01
    ],
    [
     119.03,
     371.28
    ],
    [
     169.35,
     383.65
    ],
    [
     195.28,
     390.02
    ],
    [
     221.2,
     396.39
    ],
    [
     271.52,
     408.77
    ],
    [
     288.77,
     413.82
    ]
   ],
   "width": 11,
   "surface": "sand",
   "s1": 286,
   "s2": 586,
   "side": 1
  },
  "rows": [
   0.14,
   0.36,
   0.55,
   0.74,
   0.9
  ],
  "pads": [
   0.1,
   0.63
  ],
  "coinGroups": [
   0.05,
   0.17,
   0.28,
   0.4,
   0.5,
   0.6,
   0.72,
   0.83
  ],
  "hazards": [
   {
    "type": "boulder",
    "f": 0.45
   },
   {
    "type": "boulder",
    "f": 0.62
   }
  ],
  "zones": [],
  "landmark": {
   "type": "arch",
   "f": 0.2,
   "lat": 60
  },
  "prog": [
   [
    "F",
    250
   ],
   [
    "L",
    60,
    120
   ],
   [
    "R",
    40,
    90
   ],
   [
    "F",
    150
   ],
   [
    "L",
    110,
    70
   ],
   [
    "F",
    120
   ],
   [
    "R",
    60,
    80
   ],
   [
    "F",
    100
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    180
   ],
   [
    "L",
    80,
    90
   ],
   [
    "R",
    50,
    70
   ],
   [
    "F",
    140
   ],
   [
    "L",
    100,
    80
   ],
   [
    "F",
    160
   ],
   [
    "L",
    70,
    120
   ],
   [
    "F",
    100
   ]
  ],
  "fix": [
   12,
   14
  ],
  "start": 150,
  "scale": 0.84
 },
 "frost": {
  "id": "frost",
  "name": "Frostbite Pass",
  "cup": "Seedling Cup",
  "order": 4,
  "theme": "frost",
  "width": 15,
  "offroad": 9,
  "mapOrder": 4,
  "bpm": 110,
  "music": "frost",
  "amb": "frost",
  "env": "ice",
  "shortcut": {
   "pts": [
    [
     133.87,
     466.92
    ],
    [
     136.11,
     484.44
    ],
    [
     175.89,
     495.21
    ],
    [
     196.39,
     500.75
    ],
    [
     216.88,
     506.3
    ],
    [
     256.66,
     517.07
    ],
    [
     266.23,
     531.89
    ]
   ],
   "width": 11,
   "surface": "ice",
   "s1": 434,
   "s2": 664,
   "side": 1
  },
  "rows": [
   0.13,
   0.32,
   0.52,
   0.72,
   0.9
  ],
  "pads": [
   0.2,
   0.8
  ],
  "coinGroups": [
   0.07,
   0.19,
   0.3,
   0.42,
   0.54,
   0.65,
   0.78,
   0.89
  ],
  "hazards": [
   {
    "type": "icicle",
    "f": 0.28
   },
   {
    "type": "icicle",
    "f": 0.5
   },
   {
    "type": "icicle",
    "f": 0.86
   }
  ],
  "zones": [
   {
    "f0": 0.55,
    "f1": 0.62,
    "surface": "ice",
    "onlyRoad": true,
    "lat": [
     -4,
     8
    ]
   }
  ],
  "landmark": {
   "type": "waterfall",
   "f": 0.6,
   "lat": 80
  },
  "prog": [
   [
    "F",
    250
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    120
   ],
   [
    "R",
    140,
    32
   ],
   [
    "F",
    40
   ],
   [
    "L",
    140,
    32
   ],
   [
    "F",
    100
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    250
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    160
   ],
   [
    "L",
    90,
    60
   ],
   [
    "F",
    100
   ]
  ],
  "fix": [
   2,
   8
  ],
  "start": 150,
  "scale": 1.2
 }
};
